version: '3'
services:
  ingress:
    restart: always
    networks:
      - default
      - ingress
  api:
    restart: always
    networks:
      - default
      - database
      - messenger
  mailer:
    restart: always
    networks:
      - default
      - messenger
  web:
    restart: always
networks:
  ingress:
    external:
      name: ingress
  database:
    external:
      name: database
  messenger:
    external:
      name: messenger
